// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtvbnbgskkttvphdjmmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0dmJuYmdza2t0dHZwaGRqbW1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NjIwMDAsImV4cCI6MjA3MDMzODAwMH0.-Qu3424rs1Ow_QAdqI1NZKVQfyxoAnOtPlfBDqry2H0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});